# Generated by Django 4.2 on 2023-04-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.IntegerField(choices=[(1, 'Star'), (2, 'Galaxy'), (3, 'Planet'), (4, 'Nebula')], default=1, verbose_name='Categories of Astronomy Events'),
            preserve_default=False,
        ),
    ]
