# Generated by Django 4.2 on 2023-04-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
