# Generated by Django 4.2 on 2023-04-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='path',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
